export const GET_ERRORS = 'GET_ERRORS'
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const SET_CURRENT_USER = "SET_CURRENT_USER"

/*  ADMIN CONSTANTS     */ 
export const REGISTER_DOCTOR = "REGISTER_DOCTOR"
export const FETCH_DOCTORS = "FETCH_DOCTORS"
export const ADMIN_LOGOUT = "ADMIN_LOGOUT"
