/*  AUTH CONSTANTS    */
export const GET_ERRORS = "GET_ERRORS"
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const SET_CURRENT_USER = "SET_CURRENT_USER"

/*   PATIENT ACTION CONSTANTS   */
export const ADD_PATIENT = "ADD_PATIENT"
export const FETCH_PATIENT = "FETCH_PATIENT"

export const ADD_RELATIVE = "ADD_RELATIVE"
export const FETCH_RELATIVES = "FETCH_RELATIVES"
export const REMOVE_SUBUSER = "REMOVE_SUBUSER"
export const UPDATE_USER = "UPDATE_USER"

export const FETCH_NOTES = "FETCH_NOTES"
